veterinary_clinic_aleix
nachoserra-domatix/cursoaeodoo2024-2 pull request #14
Opened 2024-11-12 14:07 UTC by aleonptic

my first module veterinary_clinic_aleix

2024-11-20 16:54 UTC, nachoserra-domatix requested changes

2024-11-20 16:54 UTC, nachoserra-domatix commented on veterinary_clinic_aleix/__manifest__.py
> +        'base',
no sería necesario poner base, ya que por ejemplo tanto sale como hr ya dependen de base.
Se puede borrar

2024-11-20 18:02 UTC, aleonptic commented on veterinary_clinic_aleix/__manifest__.py
> +        'base',
borrado!

2024-12-05 16:40 UTC, nachoserra-domatix approved these changes

2026-04-07 20:34 UTC, closed without merging